# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Conformity Template Scanner Pipeline
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm version
    # - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Cloud One Conformity Pipeline Scanner
      uses: raphabot/conformity-template-scanner-pipeline@v1
      with:
        apikey: ${{ secrets.apikey }}
        region: us-west-2
        acceptedQty: 1
        template: s3.template.yaml
    - run: echo "Works!"
